CREATE TABLE applog (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id VARCHAR(255),
    user_id VARCHAR(255),
    PRIMARY KEY (log_id)
);


CREATE TABLE actionproperties (
    properties_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    location_x DOUBLE PRECISION,
    location_y DOUBLE PRECISION,
    page_from VARCHAR(255),
    page_to VARCHAR(255),
    viewer_id VARCHAR(255),
    PRIMARY KEY (properties_id)
);


CREATE TABLE actions (
    actions_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    action_time TIMESTAMPTZ,
    action_type INTEGER,
    log_id BIGINT,
    properties_id BIGINT,
    PRIMARY KEY (actions_id),
    CONSTRAINT fk_actions_applog FOREIGN KEY (log_id) REFERENCES applog (log_id),
    CONSTRAINT fk_actions_actionproperties FOREIGN KEY (properties_id) REFERENCES actionproperties (properties_id)
);
